/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.fabricmc.fabric.api.item.v1.FabricItemSettings
 *  net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents
 *  net.minecraft.class_1761
 *  net.minecraft.class_1792
 *  net.minecraft.class_1792$class_1793
 *  net.minecraft.class_1802
 *  net.minecraft.class_1935
 *  net.minecraft.class_2378
 *  net.minecraft.class_2960
 *  net.minecraft.class_3611
 *  net.minecraft.class_7923
 */
package net.romeosnowblitz.hmh2.item;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.class_1761;
import net.minecraft.class_1792;
import net.minecraft.class_1802;
import net.minecraft.class_1935;
import net.minecraft.class_2378;
import net.minecraft.class_2960;
import net.minecraft.class_3611;
import net.minecraft.class_7923;
import net.romeosnowblitz.hmh2.Hmh2;
import net.romeosnowblitz.hmh2.fluid.ModFluids;
import net.romeosnowblitz.hmh2.item.ModItemGroup;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.AbsorptionAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.BadOmenAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.BlindnessAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.ConduitPowerAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.DarknessAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.DolphinsGraceAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.FireResistanceAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.GlowingAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.HasteAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.HealthBoostAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.HeroOfTheVilliageAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.HungerAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.InstantDamageAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.InstantHealthAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.InvisibilityAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.JumpBoostAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.LevitationAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.LuckAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.MiningFatigueAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.NauseaAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.NightVisionAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.PoisonAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.RegenerationAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.ResistanceAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.SaturationAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.SlowFallingAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.SlownessAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.SpeedAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.StrengthAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.UnLuckAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.WaterBreathingAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.WeaknessAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.amulets.WitherAmuletItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.AlightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.BlightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.BrightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.FightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.FlightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.FrightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.KnightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.LightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.MightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.SightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.charms.SlightCharmItem;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.AbsorptionBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.BadLuckBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.BadOmenBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.BlindnessBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.ConduitPowerBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.DarknessBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.DolphinsGraceBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.FireImmunityBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.GlowingBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.HasteBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.HealthBoostBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.HungerBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.InstantDamageBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.InstantHealthBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.InvisibilityBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.JumpBoostBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.LeveitationBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.LuckBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.MiningFatigueBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.NauseaBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.NightVisionBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.PoisonBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.RegenerationBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.ResistanceBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.SaturationBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.SlowFallingBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.SlownessBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.SpeedBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.StrengthBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.VillageHeroBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.WaterBreathingBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.WeaknessBucket;
import net.romeosnowblitz.hmh2.item.custom.magic.fluids.WitherBucket;

public class MagicItems {
    public static final class_1792 AMBER = MagicItems.registerItem("amber", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 ANDALUSITE = MagicItems.registerItem("andalusite", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AQUAMARINE = MagicItems.registerItem("aquamarine", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 CITRINE = MagicItems.registerItem("citrine", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 DIOPSIDE = MagicItems.registerItem("diopside", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 GARNET = MagicItems.registerItem("garnet", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 HESSONITE = MagicItems.registerItem("hessonite", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 MALICHITE = MagicItems.registerItem("malichite", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 MOONSTONE = MagicItems.registerItem("moonstone", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 OPAL = MagicItems.registerItem("opal", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 PERIDOT = MagicItems.registerItem("peridot", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 PREHNITE = MagicItems.registerItem("prehnite", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 RUBY = MagicItems.registerItem("ruby", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SAPPHIRE = MagicItems.registerItem("sapphire", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SMOKY_QUARTZ = MagicItems.registerItem("smoky_quartz", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SPESSARITE = MagicItems.registerItem("spessarite", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SPHENE = MagicItems.registerItem("sphene", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SPINEL = MagicItems.registerItem("spinel", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TANZANITE = MagicItems.registerItem("tanzanite", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TOPAZ = MagicItems.registerItem("topaz", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TORMALINE = MagicItems.registerItem("tormaline", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TSAVORITE = MagicItems.registerItem("tsavorite", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 ZIRCON = MagicItems.registerItem("zircon", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMBER_LOCKET = MagicItems.registerItem("amber_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMETHYST_LOCKET = MagicItems.registerItem("amethyst_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 ANDALUSITE_LOCKET = MagicItems.registerItem("andalusite_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AQUAMARINE_LOCKET = MagicItems.registerItem("aquamarine_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 CHARCOAL_LOCKET = MagicItems.registerItem("charcoal_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 CITRINE_LOCKET = MagicItems.registerItem("citrine_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 COAL_LOCKET = MagicItems.registerItem("coal_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 COPPER_LOCKET = MagicItems.registerItem("copper_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 DIAMOND_LOCKET = MagicItems.registerItem("diamond_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 DIOPSIDE_LOCKET = MagicItems.registerItem("diopside_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 EMERALD_LOCKET = MagicItems.registerItem("emerald_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 FLINT_LOCKET = MagicItems.registerItem("flint_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 GARNET_LOCKET = MagicItems.registerItem("garnet_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 GOLD_LOCKET = MagicItems.registerItem("gold_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 HESSONITE_LOCKET = MagicItems.registerItem("hessonite_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 IRON_LOCKET = MagicItems.registerItem("iron_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 LAPIS_LOCKET = MagicItems.registerItem("lapis_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 MALICHITE_LOCKET = MagicItems.registerItem("malichite_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 MOONSTONE_LOCKET = MagicItems.registerItem("moonstone_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 OPAL_LOCKET = MagicItems.registerItem("opal_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 PERIDOT_LOCKET = MagicItems.registerItem("peridot_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 PREHNITE_LOCKET = MagicItems.registerItem("prehnite_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SPESSARITE_LOCKET = MagicItems.registerItem("spessarite_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 RUBY_LOCKET = MagicItems.registerItem("ruby_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SAPPHIRE_LOCKET = MagicItems.registerItem("sapphire_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SMOKY_QUARTZ_LOCKET = MagicItems.registerItem("smoky_quartz_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SPHENE_LOCKET = MagicItems.registerItem("sphene_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SPINEL_LOCKET = MagicItems.registerItem("spinel_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TANZANITE_LOCKET = MagicItems.registerItem("tanzanite_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TOPAZ_LOCKET = MagicItems.registerItem("topaz_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TORMALINE_LOCKET = MagicItems.registerItem("tormaline_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 TSAVORITE_LOCKET = MagicItems.registerItem("tsavorite_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 ZIRCON_LOCKET = MagicItems.registerItem("zircon_locket", new class_1792((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_ACCELERATION = MagicItems.registerItem("amulet_of_acceleration", new SpeedAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_ANTIGRAVITY = MagicItems.registerItem("amulet_of_antigravity", new LevitationAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(100)));
    public static final class_1792 AMULET_OF_ARTHRITIS = MagicItems.registerItem("amulet_of_arthritis", new MiningFatigueAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(100)));
    public static final class_1792 AMULET_OF_BAD_LUCK = MagicItems.registerItem("amulet_of_bad_luck", new UnLuckAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(64)));
    public static final class_1792 AMULET_OF_BRICKS = MagicItems.registerItem("amulet_of_bricks", new InstantDamageAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(10)));
    public static final class_1792 AMULET_OF_BRO_YOU_GOTTA_TRY_THIS = MagicItems.registerItem("amulet_of_bro_you_gotta_try_this", new NauseaAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_BUBBLES = MagicItems.registerItem("amulet_of_bubbles", new WaterBreathingAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_CLOAKING = MagicItems.registerItem("amulet_of_cloaking", new InvisibilityAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(100)));
    public static final class_1792 AMULET_OF_CLOSED_EYES = MagicItems.registerItem("amulet_of_closed_eyes", new BlindnessAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_CLOVERS = MagicItems.registerItem("amulet_of_clovers", new LuckAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(64)));
    public static final class_1792 AMULET_OF_DECAY = MagicItems.registerItem("amulet_of_decay", new WitherAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_ENDURANCE = MagicItems.registerItem("amulet_of_endurance", new AbsorptionAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(100)));
    public static final class_1792 AMULET_OF_EXCAVATION = MagicItems.registerItem("amulet_of_excavation", new HasteAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_EXTRA_LOVE = MagicItems.registerItem("amulet_of_extra_love", new HealthBoostAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(100)));
    public static final class_1792 AMULET_OF_FLAMELESSNESS = MagicItems.registerItem("amulet_of_flamelessness", new FireResistanceAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(128)));
    public static final class_1792 AMULET_OF_FRAILTY = MagicItems.registerItem("amulet_of_frailty", new WeaknessAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_GILLS = MagicItems.registerItem("amulet_of_gills", new ConduitPowerAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_GLUTTONY = MagicItems.registerItem("amulet_of_gluttony", new HungerAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(64)));
    public static final class_1792 AMULET_OF_HEALING = MagicItems.registerItem("amulet_of_healing", new RegenerationAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(32)));
    public static final class_1792 AMULET_OF_HERCULES = MagicItems.registerItem("amulet_of_hercules", new StrengthAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(10)));
    public static final class_1792 AMULET_OF_ILLUMINATION = MagicItems.registerItem("amulet_of_illumination", new GlowingAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_LEAPING = MagicItems.registerItem("amulet_of_leaping", new JumpBoostAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(128)));
    public static final class_1792 AMULET_OF_NIGHT_SIGHT = MagicItems.registerItem("amulet_of_night_sight", new NightVisionAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_NOURISHMENT = MagicItems.registerItem("amulet_of_nourishment", new SaturationAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_OLYMPIC_SWIMMING = MagicItems.registerItem("amulet_of_olympic_swimming", new DolphinsGraceAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_RAIDS = MagicItems.registerItem("amulet_of_raids", new BadOmenAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(32)));
    public static final class_1792 AMULET_OF_REJUVINATION = MagicItems.registerItem("amulet_of_rejuvination", new InstantHealthAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_SHADOWS = MagicItems.registerItem("amulet_of_shadows", new DarknessAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_SHIELDING = MagicItems.registerItem("amulet_of_shielding", new ResistanceAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(32)));
    public static final class_1792 AMULET_OF_SICKENING = MagicItems.registerItem("amulet_of_sickening", new PoisonAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(16)));
    public static final class_1792 AMULET_OF_THE_PHANTOM = MagicItems.registerItem("amulet_of_the_phantom", new SlowFallingAmuletItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 AMULET_OF_THE_TORTISE = MagicItems.registerItem("amulet_of_the_tortise", new SlownessAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(64)));
    public static final class_1792 AMULET_OF_THE_VILLAGE_HERO = MagicItems.registerItem("amulet_of_the_village_hero", new HeroOfTheVilliageAmuletItem((class_1792.class_1793)new FabricItemSettings().maxDamage(100)));
    public static final class_1792 FIGHT_CHARM = MagicItems.registerItem("fight_charm", new FightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 LIGHT_CHARM = MagicItems.registerItem("light_charm", new LightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 MIGHT_CHARM = MagicItems.registerItem("might_charm", new MightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SIGHT_CHARM = MagicItems.registerItem("sight_charm", new SightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 FLIGHT_CHARM = MagicItems.registerItem("flight_charm", new FlightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 SLIGHT_CHARM = MagicItems.registerItem("slight_charm", new SlightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 ALIGHT_CHARM = MagicItems.registerItem("alight_charm", new AlightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 BLIGHT_CHARM = MagicItems.registerItem("blight_charm", new BlightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 BRIGHT_CHARM = MagicItems.registerItem("bright_charm", new BrightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 FRIGHT_CHARM = MagicItems.registerItem("fright_charm", new FrightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 KNIGHT_CHARM = MagicItems.registerItem("knight_charm", new KnightCharmItem((class_1792.class_1793)new FabricItemSettings()));
    public static final class_1792 ABSORPTION_FLUID = MagicItems.registerItem("absorption_fluid", new AbsorptionBucket((class_3611)ModFluids.ABSORPTION_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 BAD_LUCK_FLUID = MagicItems.registerItem("bad_luck_fluid", new BadLuckBucket((class_3611)ModFluids.BAD_LUCK_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 BAD_OMEN_FLUID = MagicItems.registerItem("bad_omen_fluid", new BadOmenBucket((class_3611)ModFluids.BAD_OMEN_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 BLINDNESS_FLUID = MagicItems.registerItem("blindness_fluid", new BlindnessBucket((class_3611)ModFluids.BLINDNESS_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 CONDUIT_POWER_FLUID = MagicItems.registerItem("conduit_power_fluid", new ConduitPowerBucket((class_3611)ModFluids.CONDUIT_POWER_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 DARKNESS_FLUID = MagicItems.registerItem("darkness_fluid", new DarknessBucket((class_3611)ModFluids.DARKNESS_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 DOLPHINS_GRACE_FLUID = MagicItems.registerItem("dolphins_grace_fluid", new DolphinsGraceBucket((class_3611)ModFluids.DOLPHINS_GRACE_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 FIRE_IMMUNITY_FLUID = MagicItems.registerItem("fire_immunity_fluid", new FireImmunityBucket((class_3611)ModFluids.FIRE_IMMUNITY_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 GLOWING_FLUID = MagicItems.registerItem("glowing_fluid", new GlowingBucket((class_3611)ModFluids.GLOWING_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 HASTE_FLUID = MagicItems.registerItem("haste_fluid", new HasteBucket((class_3611)ModFluids.HASTE_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 HEALTH_BOOST_FLUID = MagicItems.registerItem("health_boost_fluid", new HealthBoostBucket((class_3611)ModFluids.HEALTH_BOOST_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 HUNGER_FLUID = MagicItems.registerItem("hunger_fluid", new HungerBucket((class_3611)ModFluids.HUNGER_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 INSTANT_DAMAGE_FLUID = MagicItems.registerItem("instant_damage_fluid", new InstantDamageBucket((class_3611)ModFluids.INSTANT_DAMAGE_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 INSTANT_HEALTH_FLUID = MagicItems.registerItem("instant_health_fluid", new InstantHealthBucket((class_3611)ModFluids.INSTANT_HEALTH_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 INVISIBILITY_FLUID = MagicItems.registerItem("invisibility_fluid", new InvisibilityBucket((class_3611)ModFluids.INVISIBILITY_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 JUMP_BOOST_FLUID = MagicItems.registerItem("jump_boost_fluid", new JumpBoostBucket((class_3611)ModFluids.JUMP_BOOST_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 LEVITATION_FLUID = MagicItems.registerItem("levitation_fluid", new LeveitationBucket((class_3611)ModFluids.LEVITATION_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 LUCK_FLUID = MagicItems.registerItem("luck_fluid", new LuckBucket((class_3611)ModFluids.LUCK_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 MINING_FATIGUE_FLUID = MagicItems.registerItem("mining_fatigue_fluid", new MiningFatigueBucket((class_3611)ModFluids.MINING_FATIGUE_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 NAUSEA_FLUID = MagicItems.registerItem("nausea_fluid", new NauseaBucket((class_3611)ModFluids.NAUSEA_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 NIGHT_VISION_FLUID = MagicItems.registerItem("night_vision_fluid", new NightVisionBucket((class_3611)ModFluids.NIGHT_VISION_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 POISON_FLUID = MagicItems.registerItem("poison_fluid", new PoisonBucket((class_3611)ModFluids.POISON_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 REGENERATION_FLUID = MagicItems.registerItem("regeneration_fluid", new RegenerationBucket((class_3611)ModFluids.REGENERATION_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 RESISTANCE_FLUID = MagicItems.registerItem("resistance_fluid", new ResistanceBucket((class_3611)ModFluids.RESISTANCE_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 SATURATION_FLUID = MagicItems.registerItem("saturation_fluid", new SaturationBucket((class_3611)ModFluids.SATURATION_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 SLOW_FALLING_FLUID = MagicItems.registerItem("slow_falling_fluid", new SlowFallingBucket((class_3611)ModFluids.SLOW_FALLING_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 SLOWNESS_FLUID = MagicItems.registerItem("slowness_fluid", new SlownessBucket((class_3611)ModFluids.SLOWNESS_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 SPEED_FLUID = MagicItems.registerItem("speed_fluid", new SpeedBucket((class_3611)ModFluids.SPEED_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 STRENGTH_FLUID = MagicItems.registerItem("strength_fluid", new StrengthBucket((class_3611)ModFluids.STRENGTH_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 VILLAGE_HERO_FLUID = MagicItems.registerItem("village_hero_fluid", new VillageHeroBucket((class_3611)ModFluids.VILLAGE_HERO_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 WATER_BREATHING_FLUID = MagicItems.registerItem("water_breathing_fluid", new WaterBreathingBucket((class_3611)ModFluids.WATER_BREATHING_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 WEAKNESS_FLUID = MagicItems.registerItem("weakness_fluid", new WeaknessBucket((class_3611)ModFluids.WEAKNESS_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));
    public static final class_1792 WITHER_FLUID = MagicItems.registerItem("wither_fluid", new WitherBucket((class_3611)ModFluids.WITHER_FLUID_STILL, (class_1792.class_1793)new FabricItemSettings().recipeRemainder(class_1802.field_8550).maxCount(1)));

    private static class_1792 registerItem(String name, class_1792 item) {
        return (class_1792)class_2378.method_10230((class_2378)class_7923.field_41178, (class_2960)new class_2960("hmh2", name), (Object)item);
    }

    public static void addItemsToItemGroup() {
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMBER);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, ANDALUSITE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AQUAMARINE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, CITRINE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, DIOPSIDE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, GARNET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, HESSONITE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, MALICHITE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, MOONSTONE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, OPAL);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, PERIDOT);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, PREHNITE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, RUBY);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SAPPHIRE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SMOKY_QUARTZ);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SPESSARITE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SPHENE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SPINEL);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TANZANITE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TOPAZ);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TORMALINE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TSAVORITE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, ZIRCON);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMBER_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, ANDALUSITE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AQUAMARINE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, CITRINE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, DIOPSIDE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, GARNET_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, HESSONITE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, MALICHITE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, MOONSTONE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, OPAL_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, PERIDOT_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, PREHNITE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, RUBY_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SAPPHIRE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SMOKY_QUARTZ_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SPESSARITE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SPHENE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SPINEL_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TANZANITE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TOPAZ_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TORMALINE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, TSAVORITE_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, ZIRCON_LOCKET);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_ACCELERATION);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_ANTIGRAVITY);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_ARTHRITIS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_BAD_LUCK);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_BRICKS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_BRO_YOU_GOTTA_TRY_THIS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_BUBBLES);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_CLOAKING);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_CLOSED_EYES);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_CLOVERS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_DECAY);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_ENDURANCE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_EXCAVATION);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_EXTRA_LOVE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_FLAMELESSNESS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_FRAILTY);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_GILLS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_GLUTTONY);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_HEALING);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_HERCULES);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_ILLUMINATION);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_LEAPING);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_NIGHT_SIGHT);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_NOURISHMENT);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_OLYMPIC_SWIMMING);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_RAIDS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_REJUVINATION);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_SHADOWS);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_SHIELDING);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_SICKENING);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_THE_PHANTOM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_THE_TORTISE);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, AMULET_OF_THE_VILLAGE_HERO);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, FIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, LIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, MIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, FLIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SLIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, ALIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, BLIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, BRIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, FRIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, KNIGHT_CHARM);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, ABSORPTION_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, BAD_LUCK_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, BAD_OMEN_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, BLINDNESS_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, CONDUIT_POWER_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, DARKNESS_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, DOLPHINS_GRACE_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, FIRE_IMMUNITY_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, GLOWING_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, HASTE_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, HEALTH_BOOST_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, HUNGER_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, INSTANT_DAMAGE_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, INSTANT_HEALTH_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, INVISIBILITY_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, JUMP_BOOST_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, LEVITATION_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, LUCK_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, MINING_FATIGUE_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, NAUSEA_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, NIGHT_VISION_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, POISON_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, REGENERATION_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, RESISTANCE_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SATURATION_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SLOW_FALLING_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SLOWNESS_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, SPEED_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, STRENGTH_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, VILLAGE_HERO_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, WATER_BREATHING_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, WEAKNESS_FLUID);
        MagicItems.addToItemGroup(ModItemGroup.MAGIC, WITHER_FLUID);
    }

    public static void addToItemGroup(class_1761 group, class_1792 item) {
        ItemGroupEvents.modifyEntriesEvent((class_1761)group).register(entries -> entries.method_45421((class_1935)item));
    }

    public static void registerModItems() {
        Hmh2.LOGGER.info("Registering Mod Items for hmh2");
        MagicItems.addItemsToItemGroup();
    }
}

