package net.romeosnowblitz.hmh2.entity.soldier_bee;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class SoldierBeeAnimations {
    public static final Animation SOLDIER_BEE_IDLE = Animation.Builder.create(0.91667f).looping()
            .addBoneAnimation("left_wing",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.0833f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5833f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_wing",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.0833f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5833f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation SOLDIER_BEE_WALK = Animation.Builder.create(0.91667f).looping()
            .addBoneAnimation("left_wing",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.0833f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5833f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167f, AnimationHelper.createRotationalVector(0f, 0f, -80f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_wing",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.0833f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5833f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167f, AnimationHelper.createRotationalVector(0f, 0f, 80f),
                                    Transformation.Interpolations.LINEAR))).build();
}
