package net.romeosnowblitz.hmh2.block;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.ExperienceDroppingBlock;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.intprovider.UniformIntProvider;
import net.romeosnowblitz.hmh2.Hmh2;
import net.romeosnowblitz.hmh2.block.custom.magic.*;
import net.romeosnowblitz.hmh2.block.custom.magic.BadEffectBlock;
import net.romeosnowblitz.hmh2.block.custom.magic.GoodEffectBlock;
import net.romeosnowblitz.hmh2.block.custom.test.ModBlockItem;
import net.romeosnowblitz.hmh2.effect.CustomEffects;
import net.romeosnowblitz.hmh2.fluid.ModFluids;
import net.romeosnowblitz.hmh2.item.custom.test.OilDust;

public class MagicBlocks {

    //Gem Generation (~48)
    public static final Block AMBER_ORE = registerBlock("amber_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block ANDALUSITE_ORE = registerBlock("andalusite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block AQUAMARINE_ORE = registerBlock("aquamarine_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block CHARCOAL_ORE = registerBlock("charcoal_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block CITRINE_ORE = registerBlock("citrine_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DIOPSIDE_ORE = registerBlock("diopside_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block GARNET_ORE = registerBlock("garnet_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block HESSONITE_ORE = registerBlock("hessonite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block MALICHITE_ORE = registerBlock("malichite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block MOONSTONE_ORE = registerBlock("moonstone_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block OPAL_ORE = registerBlock("opal_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block PERIDOT_ORE = registerBlock("peridot_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block PREHNITE_ORE = registerBlock("prehnite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block RUBY_ORE = registerBlock("ruby_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block SAPPHIRE_ORE = registerBlock("sapphire_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block SMOKY_QUARTZ_ORE = registerBlock("smoky_quartz_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block SPESSARITE_ORE = registerBlock("spessarite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block SPHENE_ORE = registerBlock("sphene_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block SPINEL_ORE = registerBlock("spinel_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block TANZANITE_ORE = registerBlock("tanzanite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block TOPAZ_ORE = registerBlock("topaz_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block TORMALINE_ORE = registerBlock("tormaline_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block TSAVORITE_ORE = registerBlock("tsavorite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block ZIRCON_ORE = registerBlock("zircon_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_AMBER_ORE = registerBlock("deepslate_amber_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_ANDALUSITE_ORE = registerBlock("deepslate_andalusite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_AQUAMARINE_ORE = registerBlock("deepslate_aquamarine_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_CHARCOAL_ORE = registerBlock("deepslate_charcoal_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_CITRINE_ORE = registerBlock("deepslate_citrine_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_DIOPSIDE_ORE = registerBlock("deepslate_diopside_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_GARNET_ORE = registerBlock("deepslate_garnet_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_HESSONITE_ORE = registerBlock("deepslate_hessonite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_MALICHITE_ORE = registerBlock("deepslate_malichite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_MOONSTONE_ORE = registerBlock("deepslate_moonstone_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_OPAL_ORE = registerBlock("deepslate_opal_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_PERIDOT_ORE = registerBlock("deepslate_peridot_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_PREHNITE_ORE = registerBlock("deepslate_prehnite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_RUBY_ORE = registerBlock("deepslate_ruby_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_SAPPHIRE_ORE = registerBlock("deepslate_sapphire_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_SMOKY_QUARTZ_ORE = registerBlock("deepslate_smoky_quartz_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_SPESSARITE_ORE = registerBlock("deepslate_spessarite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_SPHENE_ORE = registerBlock("deepslate_sphene_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_SPINEL_ORE = registerBlock("deepslate_spinel_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_TANZANITE_ORE = registerBlock("deepslate_tanzanite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_TOPAZ_ORE = registerBlock("deepslate_topaz_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_TORMALINE_ORE = registerBlock("deepslate_tormaline_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_TSAVORITE_ORE = registerBlock("deepslate_tsavorite_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);
    public static final Block DEEPSLATE_ZIRCON_ORE = registerBlock("deepslate_zircon_ore", new ExperienceDroppingBlock(FabricBlockSettings.create().strength(3.0f, 3.0f).sounds(BlockSoundGroup.DEEPSLATE).requiresTool(), UniformIntProvider.create(2, 6)), true);

    public static final Block ANDALUSITE_DUST = registerBlock("andalusite_dust", new MagicBadDust(StatusEffects.MINING_FATIGUE, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block DIOPSIDE_DUST = registerBlock("diopside_dust", new MagicBadDust(StatusEffects.BAD_OMEN, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block GARNET_DUST = registerBlock("garnet_dust", new MagicBadDust(CustomEffects.SPIDER_EFFECT, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block MALICHITE_DUST = registerBlock("malichite_dust", new MagicBadDust(StatusEffects.HUNGER, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block MOONSTONE_DUST = registerBlock("moonstone_dust", new MagicBadDust(StatusEffects.SLOWNESS, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block PREHNITE_DUST = registerBlock("prehnite_dust", new MagicBadDust(StatusEffects.POISON, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block SMOKY_QUARTZ_DUST = registerBlock("smoky_quartz_dust", new MagicBadDust(StatusEffects.WITHER, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block TOPAZ_DUST = registerBlock("topaz_dust", new MagicBadDust(StatusEffects.UNLUCK, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block AMETHYST_DUST = registerBlock("amethyst_dust", new MagicBadDust(StatusEffects.NAUSEA, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block COPPER_DUST = registerBlock("copper_dust", new MagicBadDust(StatusEffects.LEVITATION, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block FLINT_DUST = registerBlock("flint_dust", new MagicBadDust(StatusEffects.BLINDNESS, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block AMBER_DUST = registerBlock("amber_dust", new MagicGoodDust(StatusEffects.FIRE_RESISTANCE, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block CITRINE_DUST = registerBlock("citrine_dust", new MagicGoodDust(StatusEffects.HEALTH_BOOST, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block HESSONITE_DUST = registerBlock("hessonite_dust", new MagicGoodDust(StatusEffects.STRENGTH, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block PERIDOT_DUST = registerBlock("peridot_dust", new MagicGoodDust(StatusEffects.JUMP_BOOST, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block RUBY_DUST = registerBlock("ruby_dust", new MagicGoodDust(StatusEffects.SATURATION, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block SAPPHIRE_DUST = registerBlock("sapphire_dust", new MagicGoodDust(StatusEffects.NIGHT_VISION, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block SPESSARITE_DUST = registerBlock("spessarite_dust", new MagicGoodDust(CustomEffects.BLOOD_FEVER, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block SPHENE_DUST = registerBlock("sphene_dust", new MagicGoodDust(StatusEffects.LUCK, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block SPINEL_DUST = registerBlock("spinel_dust", new MagicGoodDust(StatusEffects.RESISTANCE, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block TORMALINE_DUST = registerBlock("tormaline_dust", new MagicGoodDust(StatusEffects.REGENERATION, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block TSAVORITE_DUST = registerBlock("tsavorite_dust", new MagicGoodDust(StatusEffects.GLOWING, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block ZIRCON_DUST = registerBlock("zircon_dust", new MagicGoodDust(StatusEffects.SLOW_FALLING, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block DIAMOND_DUST = registerBlock("diamond_dust", new MagicGoodDust(StatusEffects.SPEED, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block EMERALD_DUST = registerBlock("emerald_dust", new MagicGoodDust(StatusEffects.HERO_OF_THE_VILLAGE, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block GOLD_DUST = registerBlock("gold_dust", new MagicGoodDust(StatusEffects.HASTE, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block IRON_DUST = registerBlock("iron_dust", new MagicGoodDust(StatusEffects.INVISIBILITY, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block LAPIS_DUST = registerBlock("lapis_dust", new MagicGoodDust(StatusEffects.ABSORPTION, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block CHARCOAL_DUST = registerBlock("charcoal_dust", new OilDust(StatusEffects.WEAKNESS, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block COAL_DUST = registerBlock("coal_dust", new OilDust(StatusEffects.DARKNESS, FabricBlockSettings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block AQUAMARINE_DUST = registerBlock("aquamarine_dust", new WetMagicDust(StatusEffects.DOLPHINS_GRACE, AbstractBlock.Settings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block OPAL_DUST = registerBlock("opal_dust", new WetMagicDust(StatusEffects.CONDUIT_POWER, AbstractBlock.Settings.create().nonOpaque().breakInstantly().noCollision()), true);
    public static final Block TANZANITE_DUST = registerBlock("tanzanite_dust", new WetMagicDust(StatusEffects.WATER_BREATHING, AbstractBlock.Settings.create().nonOpaque().breakInstantly().noCollision()), true);



    public static final Block BAD_LUCK_FLUID_BLOCK = registerBlock("bad_luck_fluid_block", new MagicBadFluidBlock(StatusEffects.UNLUCK, ModFluids.BAD_LUCK_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block BAD_OMEN_FLUID_BLOCK = registerBlock("bad_omen_fluid_block", new MagicBadFluidBlock(StatusEffects.BAD_OMEN, ModFluids.BAD_OMEN_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block BLINDNESS_FLUID_BLOCK = registerBlock("blindness_fluid_block", new MagicBadFluidBlock(StatusEffects.BLINDNESS, ModFluids.BLINDNESS_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block DARKNESS_FLUID_BLOCK = registerBlock("darkness_fluid_block", new MagicBadFluidBlock(StatusEffects.DARKNESS, ModFluids.DARKNESS_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block HUNGER_FLUID_BLOCK = registerBlock("hunger_fluid_block", new MagicBadFluidBlock(StatusEffects.HUNGER, ModFluids.HUNGER_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block INSTANT_DAMAGE_FLUID_BLOCK = registerBlock("instant_damage_fluid_block", new MagicBadFluidBlock(CustomEffects.SPIDER_EFFECT, ModFluids.INSTANT_DAMAGE_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block MINING_FATIGUE_FLUID_BLOCK = registerBlock("mining_fatigue_fluid_block", new MagicBadFluidBlock(StatusEffects.MINING_FATIGUE, ModFluids.MINING_FATIGUE_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block NAUSEA_FLUID_BLOCK = registerBlock("nausea_fluid_block", new MagicBadFluidBlock(StatusEffects.NAUSEA, ModFluids.NAUSEA_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block POISON_FLUID_BLOCK = registerBlock("poison_fluid_block", new MagicBadFluidBlock(StatusEffects.POISON, ModFluids.POISON_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block SLOWNESS_FLUID_BLOCK = registerBlock("slowness_fluid_block", new MagicBadFluidBlock(StatusEffects.SLOWNESS, ModFluids.SLOWNESS_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block WEAKNESS_FLUID_BLOCK = registerBlock("weakness_fluid_block", new MagicBadFluidBlock(StatusEffects.WEAKNESS, ModFluids.WEAKNESS_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block WITHER_FLUID_BLOCK = registerBlock("wither_fluid_block", new MagicBadFluidBlock(StatusEffects.WITHER, ModFluids.WITHER_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block ABSORPTION_FLUID_BLOCK = registerBlock("absorption_fluid_block", new MagicGoodFluidBlock(StatusEffects.ABSORPTION, ModFluids.ABSORPTION_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block CONDUIT_POWER_FLUID_BLOCK = registerBlock("conduit_power_fluid_block", new MagicGoodFluidBlock(StatusEffects.CONDUIT_POWER, ModFluids.CONDUIT_POWER_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block DOLPHINS_GRACE_FLUID_BLOCK = registerBlock("dolphins_grace_fluid_block", new MagicGoodFluidBlock(StatusEffects.DOLPHINS_GRACE, ModFluids.DOLPHINS_GRACE_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block FIRE_IMMUNITY_FLUID_BLOCK = registerBlock("fire_immunity_fluid_block", new MagicGoodFluidBlock(StatusEffects.FIRE_RESISTANCE, ModFluids.FIRE_IMMUNITY_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block GLOWING_FLUID_BLOCK = registerBlock("glowing_fluid_block", new MagicGoodFluidBlock(StatusEffects.GLOWING, ModFluids.GLOWING_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block HASTE_FLUID_BLOCK = registerBlock("haste_fluid_block", new MagicGoodFluidBlock(StatusEffects.HASTE, ModFluids.HASTE_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block HEALTH_BOOST_FLUID_BLOCK = registerBlock("health_boost_fluid_block", new MagicGoodFluidBlock(StatusEffects.HEALTH_BOOST, ModFluids.HEALTH_BOOST_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block INSTANT_HEALTH_FLUID_BLOCK = registerBlock("instant_health_fluid_block", new MagicGoodFluidBlock(CustomEffects.BLOOD_FEVER, ModFluids.INSTANT_HEALTH_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block INVISIBILITY_FLUID_BLOCK = registerBlock("invisibility_fluid_block", new MagicGoodFluidBlock(StatusEffects.INVISIBILITY, ModFluids.INVISIBILITY_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block JUMP_BOOST_FLUID_BLOCK = registerBlock("jump_boost_fluid_block", new MagicGoodFluidBlock(StatusEffects.JUMP_BOOST, ModFluids.JUMP_BOOST_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block LEVITATION_FLUID_BLOCK = registerBlock("levitation_fluid_block", new MagicGoodFluidBlock(StatusEffects.LEVITATION, ModFluids.LEVITATION_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block LUCK_FLUID_BLOCK = registerBlock("luck_fluid_block", new MagicGoodFluidBlock(StatusEffects.LUCK, ModFluids.LUCK_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
     public static final Block NIGHT_VISION_FLUID_BLOCK = registerBlock("night_vision_fluid_block", new MagicGoodFluidBlock(StatusEffects.NIGHT_VISION, ModFluids.NIGHT_VISION_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block REGENERATION_FLUID_BLOCK = registerBlock("regeneration_fluid_block", new MagicGoodFluidBlock(StatusEffects.REGENERATION, ModFluids.REGENERATION_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block RESISTANCE_FLUID_BLOCK = registerBlock("resistance_fluid_block", new MagicGoodFluidBlock(StatusEffects.RESISTANCE, ModFluids.RESISTANCE_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block SATURATION_FLUID_BLOCK = registerBlock("saturation_fluid_block", new MagicGoodFluidBlock(StatusEffects.SATURATION, ModFluids.SATURATION_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block SLOW_FALLING_FLUID_BLOCK = registerBlock("slow_falling_fluid_block", new MagicGoodFluidBlock(StatusEffects.SLOW_FALLING, ModFluids.SLOW_FALLING_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block SPEED_FLUID_BLOCK = registerBlock("speed_fluid_block", new MagicGoodFluidBlock(StatusEffects.SPEED, ModFluids.SPEED_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block STRENGTH_FLUID_BLOCK = registerBlock("strength_fluid_block", new MagicGoodFluidBlock(StatusEffects.STRENGTH, ModFluids.STRENGTH_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block VILLAGE_HERO_FLUID_BLOCK = registerBlock("village_hero_fluid_block", new MagicGoodFluidBlock(StatusEffects.HERO_OF_THE_VILLAGE, ModFluids.VILLAGE_HERO_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);
    public static final Block WATER_BREATHING_FLUID_BLOCK = registerBlock("water_breathing_fluid_block", new MagicGoodFluidBlock(StatusEffects.WATER_BREATHING, ModFluids.WATER_BREATHING_FLUID_STILL, FabricBlockSettings.create().noCollision().nonOpaque().dropsNothing().replaceable()), false);

    public static final Block ANDALUSITE_BLOCK = registerBlock("andalusite_block", new BadEffectBlock(StatusEffects.MINING_FATIGUE, FabricBlockSettings.create()), true);
    public static final Block DIOPSIDE_BLOCK = registerBlock("diopside_block", new BadEffectBlock(StatusEffects.BAD_OMEN, FabricBlockSettings.create()), true);
    public static final Block GARNET_BLOCK = registerBlock("garnet_block", new BadEffectBlock(CustomEffects.SPIDER_EFFECT, FabricBlockSettings.create()), true);
    public static final Block MALICHITE_BLOCK = registerBlock("malichite_block", new BadEffectBlock(StatusEffects.HUNGER, FabricBlockSettings.create()), true);
    public static final Block MOONSTONE_BLOCK = registerBlock("moonstone_block", new BadEffectBlock(StatusEffects.SLOWNESS, FabricBlockSettings.create()), true);
    public static final Block PREHNITE_BLOCK = registerBlock("prehnite_block", new BadEffectBlock(StatusEffects.POISON, FabricBlockSettings.create()), true);
    public static final Block SMOKY_QUARTZ_BLOCK = registerBlock("smoky_quartz_block", new BadEffectBlock(StatusEffects.WITHER, FabricBlockSettings.create()), true);
    public static final Block TOPAZ_BLOCK = registerBlock("topaz_block", new BadEffectBlock(StatusEffects.UNLUCK, FabricBlockSettings.create()), true);
    public static final Block AMBER_BLOCK = registerBlock("amber_block", new GoodEffectBlock(StatusEffects.FIRE_RESISTANCE, FabricBlockSettings.create()), true);
    public static final Block AQUAMARINE_BLOCK = registerBlock("aquamarine_block", new GoodEffectBlock(StatusEffects.DOLPHINS_GRACE, AbstractBlock.Settings.create()), true);
    public static final Block CITRINE_BLOCK = registerBlock("citrine_block", new GoodEffectBlock(StatusEffects.HEALTH_BOOST, FabricBlockSettings.create()), true);
    public static final Block HESSONITE_BLOCK = registerBlock("hessonite_block", new GoodEffectBlock(StatusEffects.STRENGTH, FabricBlockSettings.create()), true);
  public static final Block OPAL_BLOCK = registerBlock("opal_block", new GoodEffectBlock(StatusEffects.CONDUIT_POWER, AbstractBlock.Settings.create()), true);
    public static final Block PERIDOT_BLOCK = registerBlock("peridot_block", new GoodEffectBlock(StatusEffects.JUMP_BOOST, FabricBlockSettings.create()), true);
    public static final Block RUBY_BLOCK = registerBlock("ruby_block", new GoodEffectBlock(StatusEffects.SATURATION, FabricBlockSettings.create()), true);
    public static final Block SAPPHIRE_BLOCK = registerBlock("sapphire_block", new GoodEffectBlock(StatusEffects.NIGHT_VISION, FabricBlockSettings.create()), true);
    public static final Block SPESSARITE_BLOCK = registerBlock("spessarite_block", new GoodEffectBlock(CustomEffects.BLOOD_FEVER, FabricBlockSettings.create()), true);
    public static final Block SPHENE_BLOCK = registerBlock("sphene_block", new GoodEffectBlock(StatusEffects.LUCK, FabricBlockSettings.create()), true);
    public static final Block SPINEL_BLOCK = registerBlock("spinel_block", new GoodEffectBlock(StatusEffects.RESISTANCE, FabricBlockSettings.create()), true);
    public static final Block TANZANITE_BLOCK = registerBlock("tanzanite_block", new GoodEffectBlock(StatusEffects.WATER_BREATHING, AbstractBlock.Settings.create()), true);
    public static final Block TORMALINE_BLOCK = registerBlock("tormaline_block", new GoodEffectBlock(StatusEffects.REGENERATION, FabricBlockSettings.create()), true);
    public static final Block TSAVORITE_BLOCK = registerBlock("tsavorite_block", new GoodEffectBlock(StatusEffects.GLOWING, FabricBlockSettings.create()), true);
    public static final Block ZIRCON_BLOCK = registerBlock("zircon_block", new GoodEffectBlock(StatusEffects.SLOW_FALLING, FabricBlockSettings.create()), true);

    private static Block registerBlock(String name, Block block, boolean item) {
        if(item){Registry.register(Registries.ITEM, new Identifier(Hmh2.MOD_ID, name), new ModBlockItem(block, new FabricItemSettings(), name));}
        return Registry.register(Registries.BLOCK, new Identifier(Hmh2.MOD_ID, name), block);
    }
}
